/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Music_Advisor;

import org.checkerframework.checker.units.qual.C;

public class App {
    private static final String SPOTIFY_AUTHORIZATION_SERVER_PATH = "https://accounts.spotify.com";
    private static final String SPOTIFY_API_SERVER_PATH = "https://api.spotify.com";
    private static final int ENTRIES_PER_PAGE = 5;
    public static void main(String[] args) throws Exception {
        String authPath = App.SPOTIFY_AUTHORIZATION_SERVER_PATH;
        String apiPath = App.SPOTIFY_API_SERVER_PATH;
        int entriesPerPage = App.ENTRIES_PER_PAGE;

        for (int i = 0; i < args.length; i++) {
            try {
                if (args[i].equals("-access")) {
                    authPath = args[i + 1];
                }
                if (args[i].equals("-resource")) {
                    apiPath = args[i + 1];
                }
                if (args[i].equals("-page")) {
                    entriesPerPage = Integer.valueOf(args[i + 1]);
                }
            } catch (NullPointerException e) {
                System.out.println("Wrong arguments");
                break;
            }
        }
        Controller controller = new Controller(new Model(authPath, apiPath, entriesPerPage), new View());
        controller.work(authPath, apiPath);
    }

    public Object getGreeting() {
        return true;
    }
}
